# Generated by Django 6.0.8 on 2026-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('lawyer', 'Lawyer'), ('legal_assistant', 'Legal Assistant'), ('accountant', 'Accountant'), ('receptionist', 'Receptionist'), ('viewer', 'Viewer')], default='viewer', max_length=30),
        ),
    ]
