# Generated by Django 6.0.8 on 2026-09-07 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_convert_case_type_to_fk'),
        ('documents', '0002_remove_document_file_document_file_path_and_more'),
        ('hearings', '0001_initial'),
        ('notifications', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_document'], name='notificatio_related_1ecb0a_idx'),
        ),
    ]
