# Generated by Django 6.0.8 on 2026-09-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('hearing_time', models.TimeField(blank=True, null=True)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('judge', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hearings', to='cases.case')),
            ],
            options={
                'ordering': ['hearing_date', 'hearing_time'],
                'indexes': [models.Index(fields=['hearing_date'], name='hearings_he_hearing_493fc5_idx'), models.Index(fields=['case'], name='hearings_he_case_id_6fbe1f_idx')],
            },
        ),
    ]
