# Generated by Django 6.0.8 on 2026-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0002_alter_hearing_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
