# Generated by Django 6.0.8 on 2026-10-05 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_alternative_phone_client_client_type'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firms.firm'),
        ),
    ]
