# Generated by Django 6.0.8 on 2026-10-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_firm'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='firms.firm'),
        ),
    ]
