# Generated by Django 6.0.8 on 2026-09-03 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('court_document', 'Court Document'), ('identification', 'Identification'), ('evidence', 'Evidence'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='legal_documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cases.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='clients.client')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='documents_d_client__75b1a2_idx'), models.Index(fields=['case'], name='documents_d_case_id_528e86_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx')],
            },
        ),
    ]
