# Generated by Django 6.0.8 on 2026-09-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_client'),
        ('clients', '0002_client_alternative_phone_client_client_type'),
        ('documents', '0002_remove_document_file_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client'),
        ),
    ]
