# Generated by Django 6.0.8 on 2026-09-01 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('court_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'), models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'), models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'), models.Index(fields=['opening_date'], name='cases_case_opening_28933a_idx'), models.Index(fields=['client'], name='cases_case_client__c6764b_idx')],
            },
        ),
    ]
