# Generated by Django 6.0.8 on 2026-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_lawyer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_party',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
