# Generated by Django 6.0.8 on 2026-09-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casetype'),
        ),
    ]
