# Generated by Django 6.0.8 on 2026-09-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_convert_case_type_to_fk'),
        ('clients', '0002_client_alternative_phone_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='clients.client'),
        ),
    ]
